[tool.poetry]
name = "Guardian"
version = "3.2.1"
description = "Custom firewall used to create private lobbies for GTA5 Online"
authors = ["TheMythologist <leekaixuan2001@gmail.com>"]
license = "LGPL-3.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
chardet = "^5.1.0"
colorama = "^0.4.6"
cx-freeze = "^6.13"
pydivert = "2.1.0"
questionary = "^1.10.0"
tqdm = "^4.64.1"
requests = "^2.28.2"
prsw = "^0.3.1"

[tool.poetry.group.dev.dependencies]
black = "^22.12.0"
isort = "^5.11.4"
flake8 = "^6.0.0"
pyproject-flake8 = "^6.0.0.post1"
pre-commit = "^2.21.0"
mypy = "^0.991"
types-colorama = "^0.4.15.4"
types-tqdm = "^4.64.7.11"
types-requests = "^2.28.11.8"

[tool.flake8]
max-line-length = 88
extend-ignore = ["E203", "E501"]

[tool.isort]
profile = "black"

[tool.mypy]
platform = "win32"
exclude = ["build/", "speed_tests/"]

[[tool.mypy.overrides]]
module = ["cx_Freeze", "pydivert", "prsw"]
ignore_missing_imports = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
